# Generated by Django 4.1.7 on 2023-03-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba_stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NbaPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
